steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospringwebapplication", "--build-arg=JAR_FILE=target/helloworld-0.0.1-SNAPSHOT.jar", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/hellospringwebapplication"]
  - name: hashicorp/terraform:latest
    entrypoint: 'sh'
    args: 
     - '-c'
     - | 
        git clone --branch seemlessflow https://github.com/anup1987/IngramMicroTerraform.git
        cd IngramMicroTerraform
        git branch
        cd modules/cloud_run
        terraform init -backend=true -backend-config="ingramterraform" -backend-config="project=ingrammicroproject" -backend-config="path=terraform.tfstate"
        terraform apply -var="imagename=gcr.io/ingrammicroproject/hellospringwebapplication:latest"  -var="serviceName=app1" -auto-approve
        ls -lart
