steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospringwebapplication", "--build-arg=JAR_FILE=target/helloworld-0.0.1-SNAPSHOT.jar", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/hellospringwebapplication"]
  - name: hashicorp/terraform:1.0.0
    entrypoint: 'sh'
    args: 
     - '-c'
     - | 
        git clone --branch gcp https://github.com/anup1987/IngramMicroTerraform.git
        cd IngramMicroTerraform
        git branch
        cd modules/cloud_run
        terraform init
        terraform apply  -var="project_id=ingrammicroproject" -var="imagename=gcr.io/$PROJECT_ID/hellospringwebapplication"  -var="deploy_run_service_name=hellospringwebapplication" -auto-approve    

